// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiiPdPjehj0f__ewywtYOdetlyo0XSbbM',
    appId: '1:794089039767:web:dfa47c8da505d38a6606d2',
    messagingSenderId: '794089039767',
    projectId: 'eazy-quizy',
    authDomain: 'eazy-quizy.firebaseapp.com',
    storageBucket: 'eazy-quizy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_cPO06W-_YsBcaTNsjreNY9s-iw94bb8',
    appId: '1:794089039767:android:86fbc531dbc8a2146606d2',
    messagingSenderId: '794089039767',
    projectId: 'eazy-quizy',
    storageBucket: 'eazy-quizy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGKUS0vB8l1Wcpumq3qP15DNqPZ6m4sM',
    appId: '1:794089039767:ios:fb1e4976aee9a2956606d2',
    messagingSenderId: '794089039767',
    projectId: 'eazy-quizy',
    storageBucket: 'eazy-quizy.firebasestorage.app',
    iosBundleId: 'com.example.eazyQuizy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGKUS0vB8l1Wcpumq3qP15DNqPZ6m4sM',
    appId: '1:794089039767:ios:fb1e4976aee9a2956606d2',
    messagingSenderId: '794089039767',
    projectId: 'eazy-quizy',
    storageBucket: 'eazy-quizy.firebasestorage.app',
    iosBundleId: 'com.example.eazyQuizy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiiPdPjehj0f__ewywtYOdetlyo0XSbbM',
    appId: '1:794089039767:web:5e3cd8c52a91f6d66606d2',
    messagingSenderId: '794089039767',
    projectId: 'eazy-quizy',
    authDomain: 'eazy-quizy.firebaseapp.com',
    storageBucket: 'eazy-quizy.firebasestorage.app',
  );

}